/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AmbulanceUnitIdRouteImport } from './routes/ambulance.$unitId'
import { Route as HospitalHospitalIdRouteImport } from './routes/hospital.$hospitalId'
import { Route as ReunifyIndexRouteImport } from './routes/reunify.index'
import { Route as ReunifyTrackingIdRouteImport } from './routes/reunify.$trackingId'
import { Route as TriageNewRouteImport } from './routes/triage.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbulanceUnitIdRoute = AmbulanceUnitIdRouteImport.update({
  id: '/ambulance/$unitId',
  path: '/ambulance/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalHospitalIdRoute = HospitalHospitalIdRouteImport.update({
  id: '/hospital/$hospitalId',
  path: '/hospital/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunifyIndexRoute = ReunifyIndexRouteImport.update({
  id: '/reunify/',
  path: '/reunify/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunifyTrackingIdRoute = ReunifyTrackingIdRouteImport.update({
  id: '/reunify/$trackingId',
  path: '/reunify/$trackingId',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageNewRoute = TriageNewRouteImport.update({
  id: '/triage/new',
  path: '/triage/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/ambulance/$unitId': typeof AmbulanceUnitIdRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/reunify/$trackingId': typeof ReunifyTrackingIdRoute
  '/triage/new': typeof TriageNewRoute
  '/reunify/': typeof ReunifyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/ambulance/$unitId': typeof AmbulanceUnitIdRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/reunify/$trackingId': typeof ReunifyTrackingIdRoute
  '/triage/new': typeof TriageNewRoute
  '/reunify': typeof ReunifyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/ambulance/$unitId': typeof AmbulanceUnitIdRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/reunify/$trackingId': typeof ReunifyTrackingIdRoute
  '/triage/new': typeof TriageNewRoute
  '/reunify/': typeof ReunifyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/command-center'
    | '/ambulance/$unitId'
    | '/hospital/$hospitalId'
    | '/reunify/$trackingId'
    | '/triage/new'
    | '/reunify/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/command-center'
    | '/ambulance/$unitId'
    | '/hospital/$hospitalId'
    | '/reunify/$trackingId'
    | '/triage/new'
    | '/reunify'
  id:
    | '__root__'
    | '/'
    | '/command-center'
    | '/ambulance/$unitId'
    | '/hospital/$hospitalId'
    | '/reunify/$trackingId'
    | '/triage/new'
    | '/reunify/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandCenterRoute: typeof CommandCenterRoute
  AmbulanceUnitIdRoute: typeof AmbulanceUnitIdRoute
  HospitalHospitalIdRoute: typeof HospitalHospitalIdRoute
  ReunifyTrackingIdRoute: typeof ReunifyTrackingIdRoute
  TriageNewRoute: typeof TriageNewRoute
  ReunifyIndexRoute: typeof ReunifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambulance/$unitId': {
      id: '/ambulance/$unitId'
      path: '/ambulance/$unitId'
      fullPath: '/ambulance/$unitId'
      preLoaderRoute: typeof AmbulanceUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$hospitalId': {
      id: '/hospital/$hospitalId'
      path: '/hospital/$hospitalId'
      fullPath: '/hospital/$hospitalId'
      preLoaderRoute: typeof HospitalHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunify/': {
      id: '/reunify/'
      path: '/reunify'
      fullPath: '/reunify/'
      preLoaderRoute: typeof ReunifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunify/$trackingId': {
      id: '/reunify/$trackingId'
      path: '/reunify/$trackingId'
      fullPath: '/reunify/$trackingId'
      preLoaderRoute: typeof ReunifyTrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage/new': {
      id: '/triage/new'
      path: '/triage/new'
      fullPath: '/triage/new'
      preLoaderRoute: typeof TriageNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandCenterRoute: CommandCenterRoute,
  AmbulanceUnitIdRoute: AmbulanceUnitIdRoute,
  HospitalHospitalIdRoute: HospitalHospitalIdRoute,
  ReunifyTrackingIdRoute: ReunifyTrackingIdRoute,
  TriageNewRoute: TriageNewRoute,
  ReunifyIndexRoute: ReunifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
