/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as HospitalHospitalIdRouteImport } from './routes/hospital.$hospitalId'
import { Route as TriageNewRouteImport } from './routes/triage.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalHospitalIdRoute = HospitalHospitalIdRouteImport.update({
  id: '/hospital/$hospitalId',
  path: '/hospital/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageNewRoute = TriageNewRouteImport.update({
  id: '/triage/new',
  path: '/triage/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/triage/new': typeof TriageNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/triage/new': typeof TriageNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/command-center': typeof CommandCenterRoute
  '/hospital/$hospitalId': typeof HospitalHospitalIdRoute
  '/triage/new': typeof TriageNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/command-center' | '/hospital/$hospitalId' | '/triage/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/command-center' | '/hospital/$hospitalId' | '/triage/new'
  id:
    | '__root__'
    | '/'
    | '/command-center'
    | '/hospital/$hospitalId'
    | '/triage/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandCenterRoute: typeof CommandCenterRoute
  HospitalHospitalIdRoute: typeof HospitalHospitalIdRoute
  TriageNewRoute: typeof TriageNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital/$hospitalId': {
      id: '/hospital/$hospitalId'
      path: '/hospital/$hospitalId'
      fullPath: '/hospital/$hospitalId'
      preLoaderRoute: typeof HospitalHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage/new': {
      id: '/triage/new'
      path: '/triage/new'
      fullPath: '/triage/new'
      preLoaderRoute: typeof TriageNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandCenterRoute: CommandCenterRoute,
  HospitalHospitalIdRoute: HospitalHospitalIdRoute,
  TriageNewRoute: TriageNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
